### PR TITLE
Update alpine to 3.8

### PR DESCRIPTION
**Pull request by marians**
For https://github.com/giantswarm/giantswarm/issues/4197

### CODE REVIEW

**Comment by marians** [comment]
Calling @giantswarm/sig-releng for help here. Do you want to take this over and either make it work or close it?

**Comment by MarcelMue** [comment]
Is this even used anywhere? We use the machine executor on circle for E2E and I am not sure if we set a image anywhere else. Can someone confirm / deny?

**Comment by kopiczko** [comment]
I haven't seen that being used.

**Comment by MarcelMue** [comment]
Yeah again, first PR 3 commits. I don't think this is used anywhere.

**Comment by marians** [comment]
The quay logs show usage by @r7vme and @corest (plus some anonymous). Maybe you know whether this repo is used at all?

https://quay.io/repository/giantswarm/docker-circleci?tab=logs

**Comment by marians** [comment]
Closing. Whoever cares about this repo can do the upgrade.

**Pull request closed without merging**
